### ISSUE TITLE
i64 parameters

### ISSUE THREAD

**Issue by kripken** [fivedots/nativeio-async-wrapper#1]
Looks like `NativeIO_Read` sends an i64 as the last param (offset), but the JS just receives a single JS variable, `offset`. That will work with BigInt support, but otherwise an i64 in C will turn into a pair of `low, high` 32-bit values.

If this is only meant to work with BigInts, then it's ok. Otherwise, it should use the helper macros emscripten has, see e.g. how `seek` works, https://github.com/emscripten-core/emscripten/blob/98691d70014d41fefdcdcc9e7e720a6281e250c9/src/library_syscall.js#L1527

**Comment by fivedots** [comment]
Thanks for the report! Fixed in https://github.com/fivedots/nativeio-async-wrapper/commit/1c8bf14b17973b653606901b7128b9f4a5e8e212
